name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:   # Allows manual triggering

env:
  REGISTRY: ghcr.io                # GitHub Container Registry
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v2
        with:
          version: 'v1.21.2'

      - name: Authenticate to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        run: |
          # Decode and set up kubeconfig
          echo "${KUBECONFIG_DATA}" | base64 -d > $HOME/.kube/config

          # Update Kubernetes deployment with the new image
          kubectl set image deployment/my-deployment my-container=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

          # Ensure the rollout is successful
          kubectl rollout status deployment/my-deployment
